services:
  app:
    build:
      context: .
      dockerfile: ./php/jenkins.Dockerfile
    image: php:latest
    container_name: auth-service
    hostname: "php"
    ports:
      - "9002:9002"  # Expose port 9000 for PHP-FPM
    # volumes:
    #   - ${PWD:-$(pwd)}:/var/www/html  # ✅ Use absolute path
    working_dir: /var/www/html
    networks:
      - nginx-auth-service-network
      - rabbitmq-network
      - microservices-db-dev
    env_file:
      - .env
    environment:
      - APP_ENV=development
      - APP_DEBUG=true

  nginx_laravel:
    build:
      context: .  # ← Root directory (consistent)
      dockerfile: ./nginx/jenkins.Dockerfile
    image: nginx:latest
    container_name: nginx-auth-service
    hostname: "nginx"
    ports:
      - "8090:80"
    # volumes:
    #   - ${PWD:-$(pwd)}:/var/www/html  # ✅ Use absolute path
    depends_on:
      - app
    networks:
      - nginx-auth-service-network
      - rabbitmq-network
      - microservices-db-dev

networks:
  nginx-auth-service-network:
    driver: bridge
  microservices-db-dev:  # Simplified network definition
    name: microservices_dev_microservices-db-dev
    external: true
  rabbitmq-network:
    name: rabbitmq_rabbitmq-network
    external: true  